### PR TITLE
Change 'Container Compliance' project name and move to security section

### PR DESCRIPTION
**Pull request by devhkr**
I ran into this project which, I first thought it's in the wrong category according to the description, is no longer active.

### CODE REVIEW

**Comment by agebhar1** [comment]
@devhkr - the obsolete message mention the _oscap-docker_ [1] tool which provides the same functionality
> Obsolete!
> This project is obsolete, the functionality is provided by the oscap-docker tool that ships with OpenSCAP.

Instead of remove the project, I suggest to replace it - what did you think?

[1] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sect-Using_OpenSCAP_with_Docker.html

**Comment by dmitrytokarev** [comment]
@devhkr it looks like https://github.com/OpenSCAP team provides docker compliance functionality as part of their https://github.com/OpenSCAP/openscap project.
See commit msg on https://github.com/OpenSCAP/container-compliance/commit/6b6090a9b3cdb05aa42b34b276f5625a36e88e9c

Here are steps of running it on RHEL: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sect-Using_OpenSCAP_with_Docker.html
Wonder if we should not remove but update this project info because security is important and we have very few compliance resources as part of awesome-docker list.

**Comment by devhkr** [comment]
Thanks for your feedbacks @agebhar1 @dmitrytokarev 

Yeah, had to read the notice again and again what it could mean. Then, also found out as you both correctly did that functionality is provided by `oscap-docker`.

 [OpenSCAP-daemon](https://github.com/OpenSCAP/openscap-daemon) seems to be the right project?

**Comment by agebhar1** [comment]
@devhkr, _oscap-docker_ is part of [OpenSCAP](https://github.com/OpenSCAP/openscap) - see @dmitrytokarev's [comment](https://github.com/veggiemonk/awesome-docker/pull/377#issuecomment-314222398) :wink: 

See also [5.2. Scanning of Docker containers and images using oscap-docker](https://github.com/OpenSCAP/openscap/blob/maint-1.2/docs/manual/manual.adoc#52-scanning-of-docker-containers-and-images-using-oscap-docker)

**Comment by devhkr** [comment]
@agebhar1 thanks for the hint, again.

OpenSCAP provides several tools and
Yes, `oscap-docker` is part of the OpenSCAP base tool.

Ok then, should I fix the project info?

**Comment by agebhar1** [comment]
from my point of view - yes

Thanks @devhkr for this update!

**Comment by devhkr** [comment]
Thanks @dmitrytokarev for your review.

Yes, I was going to add a link to the usage section. However, the documentation is quite huge. For starters, the first two sections (introduction and installation guide) are relevant in order to understand and to use the `oscap-docker` tool. Maybe, replace the current link to the documentation site?

**Comment by dmitrytokarev** [comment]
I gave it a second thought...
The link to the docs is this: https://github.com/OpenSCAP/openscap/blob/maint-1.2/docs/manual/manual.adoc#scanning-of-docker-containers-and-images-using-oscap-docker
but it'd be pain to maintain, so probably will just leave this as is - let curious minds find the docs they need! 😸

**Comment by veggiemonk** [comment]
@dmitrytokarev @agebhar1 @devhkr Good team work 👍

**Pull request merged**
