### PR TITLE
Fix Travis Build 

### PR DESCRIPTION
**Pull request by ReadmeCritic**

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
FYI http://www.smartjava.org/ is down at the moment @josdirksen

**Comment by josdirksen** [comment]
Thanks for the update. Looking into it right now. Seems an issue with my DNS provider :(

**Comment by veggiemonk** [comment]
Thanks a lot @ReadmeCritic 

@josdirksen just in case, your article is here too: https://dzone.com/articles/10-practical-docker-tips-for-day-to-day-docker-usa it is safer to put that link but it might bring less traffic to your site. Your call.

**Comment by josdirksen** [comment]
Well it took some effort, but we're back. @ReadmeCritic if you'd be so nice to put the link to my site back again :)

**Comment by veggiemonk** [comment]
@josdirksen done. https://github.com/veggiemonk/awesome-docker/commit/b86e72ff762d56e5f30f7d8cc5d4c13e0968d972

**Comment by josdirksen** [comment]
Thanks!

**Pull request merged**
