### PR TITLE
Added Selenoid

### PR DESCRIPTION
**Pull request by vania-pooh**
**[https://github.com/aerokube/selenoid]**

**[This is an alternative faster Selenium hub implementation using Docker containers to start isolated browsers. Very simple and useful for local automatic tests development and for organizing big Selenium clusters.]**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- The project submitted is conform to the quality standards outlined in the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- Go to the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md) and read it again.

RULES (because you probably didn't read the guidelines): 
* ORDER: The entries are in lexical order (English letter order) 
* CREDIT: Each entry must contains the name of the author with a link to its github account!
* LINK: the link should be to the source code (https://github/account/project) not the website (https://myproject.io <- no!)
* MONEY: indicates if one needs a paying subscription to use that project you could just add ($$$) next to the name ([my project - $$$] (link to my project) )

### CODE REVIEW

**Comment by Moshe-Immerman** [comment]
Hi 

Selenoid certainly looks like an awesome project, You should probably do a PR for this repo: [awesome-selenium](https://github.com/christian-bromann/awesome-selenium#docker) 

This is definitely a good example of using docker, but if awesome-docker were to include all good projects built on docker, the list would be very, very long.  

Maybe you should try find a list/aggregator of docker projects and add it there, and then we can possibly link to the aggregator?

The awesome docker team

@vegasbrianc @gesellix @dmitrytokarev @moshe-immerman @veggiemonk

**Comment by vania-pooh** [comment]
@Moshe-Immerman already done a PR there. However I noticed that you already have very similar Zalenium project in the same section of your repo. So according to your logic it also should not be present.

**Comment by Moshe-Immerman** [comment]
Correct, according to my logic Zalenium and friends should be removed, leaving only tools that test docker images/config files. 

@veggiemonk @dmitrytokarev  what are your thoughts? Is the scope in CONTRIBUTING.md intentionally vague/wide or is their room to refine it?

**Comment by Moshe-Immerman** [comment]
Or perhaps we should create a *Docker Use Cases/Examples* section?

**Comment by veggiemonk** [comment]
@vania-pooh Thank you for your contribution, stay tuned as we discussed how and where we should organize those links.

@Moshe-Immerman Good point. Before the latest refactor of the list, we had a section called "Useful docker images" but it was not easily maintainable due to the amount of possible entries that section could have. 
But I would like also for people to be able to contribute so here is the idea: 
* We can create another file such `docker-images.md` or something similar. In there we list and let people list their own docker images. We would link the file in the `README.md`. We would probably need some help for that but the awesome docker team is bug enough now so that we can actually add some of the best docker images. I wanted to add https://github.com/sameersbn/docker-gitlab but never had a real place for it. 

or 

* we just deny that and redirect people to https://github.com/Kickball/awesome-selfhosted as this is where most of these images should already be. 

Awesome docker team @Moshe-Immerman @devhkr @gesellix @vegasbrianc @agebhar1 @dmitrytokarev what do you think about it?

**Comment by vania-pooh** [comment]
@veggiemonk sure.

**Comment by veggiemonk** [comment]
@vania-pooh Again thank you for your contribution. After evaluating the cost of maintaining such a list most members of the team agree that we feel it is too much to maintain. We would like to redirect you towards another awesome list that might be more suited to that topic. Such as https://github.com/Kickball/awesome-selfhosted or maybe try this one: https://github.com/kahun/awesome-sysadmin

@Moshe-Immerman  Nice catch and good job! 
Could you also remove those entries which should not be there such as the other selenium images if you have the time? If not, I'll do it another day...

**Comment by dmitrytokarev** [comment]
@vania-pooh thank you for the PR! But sorry it didn't get listed.
Awesome docker team will update the contribution guidelines to be more clear about what projects get listed.

**Comment by vania-pooh** [comment]
No issue. Already merged to `awesome-selenium`.

**Pull request closed without merging**
