### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by umiddelb**
Hi,

I've added two links for the Raspberry Pi (& ARM) section.

Cheers
Uli

### CODE REVIEW

**Comment by veggiemonk** [comment]
You forgot to fix the link in menu. If you change the name of the "Raspberry Pi" section, please adapt it in the menu!

**Comment by umiddelb** [comment]
done

**Comment by veggiemonk** [comment]
Thanks! Nice one!

**Comment by umiddelb** [comment]
Your welcome, thank you for putting this all together!

**Pull request merged**
