### PR TITLE
dockerize: supported version

### PR DESCRIPTION
**Pull request by alexeyshockov**
The original version has been stuck without new releases for years now, looks like this fork has been accepted by the most of the community

### CODE REVIEW

**Review by mashb1t — APPROVED** [review]
@alexeyshockov thank you for the update!

**Review by mashb1t — CHANGES_REQUESTED** [review]
@alexeyshockov one small thing: could you please add powerman to the list of linked user accounts so the reference works correctly? 
We'll merge the update afterwards.
Thank you!

**Comment by alexeyshockov** [comment]
@mashb1t, sure, added

**Review by mashb1t — APPROVED** [review]
@alexeyshockov thanks, lgtm 👍

**Pull request merged**
