### PR TITLE
updates alerting entry

### PR DESCRIPTION
**Pull request by uschtwill**
mentions new secure mode for prod use

### CODE REVIEW

**Comment by veggiemonk** [comment]
@uschtwill this link `http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/` appears more than once in the file.

could you create a link (see the end of the file if you want example) ?

thanks a lot

**Comment by uschtwill** [comment]
like so?

**Comment by veggiemonk** [comment]
@uschtwill Yay! thanks a lot. 
It makes links easier to maintain. Thanks for fixing it!

**Comment by uschtwill** [comment]
Thank you1 :)

**Pull request merged**
