### PR TITLE
Add https://github.com/chentex/random-logger

### PR DESCRIPTION
**Pull request by chentex**
Hello I wanted to share this docker image

[Random Logger](https://github.com/chentex/random-logger)

It's a simple docker images that generates generates random log messages in the container, useful to test log forwarding configurations.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- The project submitted is conform to the quality standards outlined in the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- Go to the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md) and read it again.

### CODE REVIEW

**Comment by devhkr** [comment]
Hi @chentex, thanks for your contribution.

Our goal is to list valuable information about docker and its resources.

We went through the repo and it needs improvements in terms of usefulness, e.g. like [logspout](https://github.com/gliderlabs/logspout).
In other words, a project should solve real problems meaning that 'random-logger' should display at least actual log messages instead of random ones.
If it is a Work in Progress, Beta version etc., please mention it in the description.

We value people's time a lot, so we recommend you to improve the project by answering the following questions:
- what is this project about?
- what does it do?
- how to use it?
- how does it compared to others from the same category?

Also we would like to help developers to make great projects.
So a good start would be to take a look at other projects.
It would be great if you come back again with an improved version and good examples.

Please let us know if you need any help.

Have a good day left and happy coding.

**Comment by veggiemonk** [comment]
Hi @chentex,

Thank you for sharing this with us. 

Do you have any use case scenario for that project ?
You say it is random but I don't see any randomness in the log. There is randomness in the log level. So the project should be called `random-log-level-generator`.

**Comment by chentex** [comment]
Thanks for your comments, 

@devhkr I'll be checking [logspout](https://github.com/gliderlabs/logspout) to see how it works and take an example on their documentation.

@veggiemonk you might be right with the name of the project; the use scenario I primarily use it for is to test logging configuration and logging drivers from Docker, I find it useful to pull from this image and just add the configurations for different logging drivers.

**Comment by veggiemonk** [comment]
@chentex if you made changes to this PR we can reopen it.

**Comment by chentex** [comment]
@veggiemonk thanks!

**Pull request closed without merging**
