### PR TITLE
Add "Local Docker DB" list to "Awesome Lists"

### PR DESCRIPTION
**Pull request by laundmo**
Adding the list of docker-compose samples for running databases made by @alexmacarthur

- [Local Docker DB](https://github.com/alexmacarthur/local-docker-db) a list of docker-compose samples for a lot of databases by [@alexmacarthur](https://github.com/alexmacarthur)

### CODE REVIEW

**Comment by mashb1t** [comment]
Hey @laundmo,
thank you for your contribution. 
As https://github.com/alexmacarthur/local-docker-db is by definition no awesome list i think the category "Demos and Examples" fits best. 
Please also keep the alphabetic order in mind.

**Review by mashb1t — CHANGES_REQUESTED** [review]
Hey @laundmo ,
thank you for your contribution.
As https://github.com/alexmacarthur/local-docker-db is by definition no awesome list i think the category "Demos and Examples" fits best.
Please also keep the alphabetic order in mind.

**Comment by laundmo** [comment]
Allright, done. It also seems like "Demos and Examples" was not sorted, so i did that. hope thats okay.

**Review by agebhar1 — APPROVED** [review]

**Comment by agebhar1** [comment]
Unfortunately the test fails due to a expired certificate from on of the links. @mashb1t how should we proceed?

**Review by mashb1t — APPROVED** [review]
@laundmo thank you for your changes, LGTM 👍 

@agebhar1 i already informed Phonito two days ago in https://github.com/veggiemonk/awesome-docker/pull/958, let's give them time until the next PR gets created.

**Pull request merged**
