### PR TITLE
adds ContainerShip & ContainerShip Cloud

### PR DESCRIPTION
**Pull request by normanjoyner**

### CODE REVIEW

**Comment by vegasbrianc** [comment]
Hi @normanjoyner Thanks for the PR! We are trying to prevent having duplicate URLS in the awesome-docker list. Could you please update your PR and only submit the link to a single category that best fits the product? Thank you!

**Comment by veggiemonk** [comment]
@vegasbrianc I guess in this particular case, it is ok because one is a service hosting and the other is a repo. So Same name, different product. I would merge it. What do you think?

**Comment by vegasbrianc** [comment]
A duplicate URL will cause the build to break from now on :( The workaround is providing a different URL page for each link. URL then URL/feature_page

**Comment by veggiemonk** [comment]
Are you sure this workaround works?
The clean way to have an URL multiple time into a file is to put URL at the end like this:
```
[containership]: https://containership.io
```
I will fix this. no biggie.

**Comment by vegasbrianc** [comment]
OK, thanks! I was not certain.

**Comment by veggiemonk** [comment]
:smile: no worries, thanks for helping :D

**Comment by normanjoyner** [comment]
Thank you both!

**Pull request merged**
