### PR TITLE
Added Testing section with selenium-docker links

### PR DESCRIPTION
**Pull request by dmitrytokarev**
Added new Testing section with selenium-docker by @SeleniumHQ and @elgalu.
Moved Pumba from Continuous Integration / Continuous Delivery to Testing section.

### CODE REVIEW

**Comment by dmitrytokarev** [comment]
@veggiemonk please review. It seems that i don't have rights to request a review ;(

**Comment by veggiemonk** [comment]
@dmitrytokarev Cool! Thanks.
By the way, we are in complete refactoring of the list. See https://github.com/veggiemonk/awesome-docker/pull/271

Now every PR must be reviewed that is part of the refactoring because some links were not really high quality and we want to keep maintain that.

So you might have to rebase master once #271 is merged. If you don't know how to do, we'll help you, it's real easy. But every PR is blocked until @vegasbrianc merge it. Is it ok for you to wait a little?

By the way, would you be interested in becoming a maintainer ?
You would be able to review PR (not this one because you made it yourself).
If that's the case, just let me know, I'll add you 😄

**Comment by dmitrytokarev** [comment]
@veggiemonk sure i can wait, will rebase once #271 is merged np.
Sure, i am cool to be a maintainer, thanks :)

**Comment by vegasbrianc** [comment]
hi @dmitrytokarev #271 is merged 👍

**Comment by veggiemonk** [comment]
@vegasbrianc Thanks!!

@dmitrytokarev your changed have been approved. Let us know if you need any help with the rebase. 
Nice section by the way, it is missing some content, do you have any idea how to improve the testing section?

**Comment by veggiemonk** [comment]
@dmitrytokarev can you also add your twitter handle in the `contributing.md`

**Comment by dmitrytokarev** [comment]
@veggiemonk will do :+1:

**Comment by dmitrytokarev** [comment]
@veggiemonk rebasing brought conflicts. Making fresh branch was quicker than resolving conflicts. Closing this PR in favor of https://github.com/veggiemonk/awesome-docker/pull/275

**Pull request closed without merging**
