### PR TITLE
adding turbo

### PR DESCRIPTION
**Pull request by ramitsurana**
* Powerful utility for Docker
* Made for easy management and usage of Docker

### CODE REVIEW

**Comment by vegasbrianc** [comment]
Hi @ramitsurana thanks for the PR. Could you please add https to your links as it is breaking the build at the moment. Thanks!

**Comment by vegasbrianc** [comment]
Cool tool @ramitsurana Thanks for the submission. I also like your snail logo 👍

**Comment by ramitsurana** [comment]
Thanks @vegasbrianc for the support. I hope @docker users like it !!

**Comment by lholznagel** [comment]
Will take a look :)
Especially the part `clean Cleans up all your docker images from your system`. Just deleted 150gb from docker

**Comment by ramitsurana** [comment]
awesome @lholznagel :+1: 
Let me know if you run into any issues.The project is at its starting phases :) Let's make it more awesome and useful.

**Pull request merged**
