### PR TITLE
Added Docker Cloud

### PR DESCRIPTION
**Pull request by senk**

### CODE REVIEW

**Comment by veggiemonk** [comment]
@senk Thanks! 

I guess we could remove tutum altogether

**Comment by veggiemonk** [comment]
Or maybe not, tutum website is still on.

**Comment by senk** [comment]
I will observe that. Docker Cloud was announced this morning i guess so maybe they will turn off the tutum page later. anyhow they have some github repos which are very tutum branded so we better leave it in the list unless it's finally shut down

**Comment by veggiemonk** [comment]
Exactly. 

Thanks a lot.

**Pull request merged**
