### PR TITLE
Proposed implementation

### PR DESCRIPTION
**Pull request by Moshe-Immerman**
Hi 

I tried to make the changes as small as possible and grouped logically to make the review as easy possible - But there is still a lot of change here.

Apologies if this PR has gone too far.

Mo

### CODE REVIEW

**Comment by devhkr** [comment]
@Moshe-Immerman Why did you open a new PR instead of making commits directly into PR #404 ?!? I really appreciate your effort into this, but the new PR is too big for review.

I also kindly remind you my following [comment](https://github.com/veggiemonk/awesome-docker/issues/393#issuecomment-318607568):
>We all value each other's contribution and time, but making smaller things speed up review time and it’s easier for the reviewers to understand the context and reason with the logic.

**Comment by Moshe-Immerman** [comment]
I didn't want to commit directly to 404 or the branch as I thought this might
be too big…
Should I cherry-pick the first 3 or 4 and commit to 404 and then rinse and
repeat?  





On Sat, Aug 26, 2017 10:12 PM, Henry notifications@github.com  wrote:
@Moshe-Immerman  Why did you open a new PR instead of making commits directly
into PR #404  ?!? I really appreciate your effort into this, but the new PR is
too big for review.

I also kindly remind you my following comment:

We all value each other's contribution and time, but making smaller things speed
up review time and it’s easier for the reviewers to understand the context and
reason with the logic.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Moshe Immerman  Technical Director  moshe@egis-software.com  Egis Software |  
www.papertrail.co.za
011 880 4411​ ​|0724821895​  Find us on a map    How did I do?  

Click on a face to provide feedback on my performance!

**Comment by devhkr** [comment]
It's up to you picking up 'refactor ...' and commit them into PR 404
All the 'move ...' commits can remain here.

By the way, you also started moving projects around. This is what we do next after we agree on the naming and reordering sections accordingly.

**Comment by veggiemonk** [comment]
see #408

**Pull request closed without merging**
