### PR TITLE
Added DockerSurfer in the web section

### PR DESCRIPTION
**Pull request by Simone-Erba**
Added DockerSurfer in the web section

https://github.com/Simone-Erba/DockerSurfer

It's a web service that allows to browse all the dependencies between the images in the Docker Registry. It allows the graphical navigation of them with a REST interface. It also calculate popularity and stability for the images. It create connections by looking at the image's layers. 

It's useful because users can notice if an image that they are using as a base for their images lose popularity or stability. A loss in popularity can mean that a new bug was discovered or that a better image was released. Low stability for an image can mean that the image is likely to unexpectedly change its layers frequently. If you don't know how to use an image or if the documentation for that image is poor, you can see how other users are using it.

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- The project submitted conforms to the quality standards outlined in the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- Go to the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md) and read it again.

**RULES (because you probably didn't read the guidelines):**

Links will be tested with [awesome_bot](https://github.com/dkhamsing/awesome_bot). Please make sure your URL to be listed is unique (do some search queries), otherwise put a link at the end of `README.md` file.
 
- FORMAT
  - Use the following format: `[Name](Link) - Description.`
  - `[Name]` should be the title of the project
  - `(Link)` should be pointing to a GitHub repository, not to a website
  - `Description.` should end with a full stop/period
  - For GitHub repositories, add the name of the author with a link to its GitHub account after the description, like `By [@author](GitHub account)`
- ORDER: The entries are in lexical order (English letter order) 
- LABEL (Optional): Add one of the following icons next to the project name like ```[Name](Link) :icon: - Description.```
  - :heavy_dollar_sign: indicates if one needs a paying subscription to use the project.
  - :construction: indicates that the project is a work in progress/beta release.
  - :skull: indicates that the project is obsolete, but still worth mentioning it.

### CODE REVIEW

**Comment by vegasbrianc** [comment]
Hi @Simone-Erba Thanks for the PR. It is a very interesting tool and I can see quite some potential here with your product. I noticed the link points to your EC2 instance DNS name. As this is something that could easily change is it possible to get a fixed domain listed?

Also, it would be great if the README is expanded to include some examples and further explanation about the different screens inside your app like the page rank. It looks really cool but it is hard for me to decipher what it is actually doing.

We are more than happy to help you get your project updated so we can include it in our list.

**Comment by Simone-Erba** [comment]
Thank you @vegasbrianc for your answer. You will hear from me again when I will have fixed the points of your list

**Comment by Simone-Erba** [comment]
Hi @vegasbrianc 
I took a permanent domain name (www.dockersurfer.com) but when I'm in my service the URL showing it's still the aws ec2 url. I hope this is not a big problem. 
I explained the different screens of the service with screenshots and I tried to explain the indexes meaning. I also added a couple of use cases and some data analysis.

**Comment by agebhar1** [comment]
Hi @Simone-Erba I think you have to update your DNS A record (https://uk.godaddy.com/help/manage-dns-zone-files-680) -- which actually is 184.168.221.4:
```
$ dig www.dockersurfer.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.dockersurfer.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35322
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.dockersurfer.com.          IN      A

;; ANSWER SECTION:
www.dockersurfer.com.   3600    IN      CNAME   dockersurfer.com.
dockersurfer.com.       600     IN      A       184.168.221.4

;; Query time: 68 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Sat Oct 21 20:36:37 CEST 2017
;; MSG SIZE  rcvd: 68
```
to your AWS IP (18.221.47.183):
```
$ dig ec2-18-221-47-183.us-east-2.compute.amazonaws.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> ec2-18-221-47-183.us-east-2.compute.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17293
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ec2-18-221-47-183.us-east-2.compute.amazonaws.com. IN A

;; ANSWER SECTION:
ec2-18-221-47-183.us-east-2.compute.amazonaws.com. 86400 IN A 18.221.47.183

;; Query time: 24 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Sat Oct 21 20:24:16 CEST 2017
;; MSG SIZE  rcvd: 94
```

I also strongly recommend to use a reverse proxy like [Apache HTTP](https://httpd.apache.org/) or [NGINX](https://nginx.org/en/) instead of exposing (Apache) Tomcat's instance.

**Comment by veggiemonk** [comment]
Hi @Simone-Erba ,

@agebhar1 is right. It's for your own safety. I was about to merge it but I realize that if I merge it now many people might find your service and even abuse it. It is a good idea to do some hardening on the server (see https://www.digitalocean.com/community/questions/best-practices-for-hardening-new-sever-in-2017) and also provide a secure access to the service (see https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04). It will allow you to learn a lot because these things have gotten incredibly easier. The experience is totally worth it.

The project is really cool but I have to say, by looking deeper into it, the code quality is really poor!
Here is why:
* There are tons of commented code [example](https://github.com/Simone-Erba/DockerSurfer/blob/master/src/main/java/indexes/indexer.java#L45) All non relevant comment must be removed.
* The JSON serialization is string concatenation which is really bad for performance and readability see [here](https://github.com/Simone-Erba/DockerSurfer/blob/master/src/main/java/servlet/Endpoint2.java#L62). Instead it might be a good idea to have a Class that contains the fields required and serialize it (you can use [Gson](https://github.com/google/gson) like most people do).
* The use of deprecated API is usually found in old project, not a new one, see [here](https://github.com/Simone-Erba/DockerSurfer/blob/master/src/main/java/searcher/GraphOperations.java#L41)
* The naming of the endpoints are `EndPoint1` `EndPoint2` `EndPoint3`. That is really bad naming because I cannot tell the difference between the 3 of them.
* Again string concatenation for HTML instead of using a proper library, see[here](https://github.com/Simone-Erba/DockerSurfer/blob/master/src/main/java/servlet/Endpoint1.java#L92). It should be using a separate front-end that query the back-end for data though the REST API. The display of data is separated from the logic of the data. It is called separation of concerns and it will save you a world of pain when things are going to change.
* Where are the tests???? No tests? Seriously?
* The webpages barely have any css which make the website looks like a form designed in 1995 on IE4. You could at least use [bootstrap](http://getbootstrap.com/) in your project or any other css framework.

The code of the project needs work since it not a prototype but an real service. As it is in Beta, it might end up in the list, but if the quality of the project doesn't improve it will be removed eventually. Are you planning on making it something usable for everyone or is it just a toy project ? Both is fine but we need to know what is the intend of the project so that we can warn people about the quality of the service they will find on the list. As mentioned in the Contribution guide lines, we strive for quality but we also allow for innovation (such as service in beta).

I hope that this will help you make the most out of this project. It is a nice project and it can get you a lot of attention if people can use it reliably. Let us know what is your intent for that project and if you need any help for it. We are here to help.

The Awesome Docker team
@vegasbrianc @devhkr @agebhar1 @Moshe-Immerman @gesellix @veggiemonk

**Comment by Simone-Erba** [comment]
Hi @veggiemonk, @vegasbrianc, and @agebhar1,

thank you for the time and the effort. First I have to say that the idea for this project it's by @innuendonh, I only implemented it in a bad way. I already knew that the code quality was really poor since it's my first project and I was in hurry. I will work on the problems pointed out by @veggiemonk and I know that there are other problems too. I think I will need some time but I don't have the urge to merge.  @agebhar1 thank you for you help, it took me a while but the proxy is up now.

**Comment by veggiemonk** [comment]
Hi @Simone-Erba ,

Great, no worries, we are here to help you get your project to high quality. But it is super difficult to improve that kind of code base so if you want people to come and contribute, the code has to be clear and understandable. We are not in a hurry to merge either. Ping us when you are ready 😄

**Comment by Simone-Erba** [comment]
Hi @veggiemonk,

can you check if the code quality is acceptable now? Thank you.
Simone

**Comment by veggiemonk** [comment]
Hi @Simone-Erba 

Nice job cleaning up the code base. 
The project has improved much. I tried it and there is a lot of potential in this project as @vegasbrianc said. Basically the project is still very much "beta" quality at the moment but it is usable. I noticed that the code quality very much improved. Although you really must start do unit testing, your future self is going to have to maintain that project (if you still planning on making it evolves) but sometimes we learn through pain and suffering. You'll understand I'm sure of it. 

So it's ok now but you can do better. And please, try to use something like http://getbootstrap.com/ for the UI. Example: http://dockersurfer.com/rest/popular/?popular=Popular+images is just links separated by `<br/>` so a doing a little bit of web development would be a good thing.

Good job and keep on improving 😄

**Comment by Simone-Erba** [comment]
Hi @veggiemonk 

I changed the structure and added some css to the [popular](http://dockersurfer.com/rest/popular/?popular=Popular+images) section but now it takes even longer to load, so I will not update it and I will search for a way to speed up the search. I will write tests about the correctness of the changes detected in the graph (new images, new users, ecc..), but I can't think about other tests. I'm sure that the graph structure is ok, because I wrote tests in the program that created the database. Do you have suggestions for other tests?

Thank you for your time, Simone

**Comment by veggiemonk** [comment]
@Simone-Erba The hardest part of testing is to start writing tests. 
This can help https://www.udemy.com/junit-tutorial-for-beginners-with-java-examples/
The process looks something like this:
* Write a test
* see it fails (run the test and it fails)
* refactor (make the test pass)
* see it passes (run the test and it passes)

Try to tests the case where something goes wrong (i.e. wrong input, the server is unreachable, the connection to the DB is closed, the network is down, and so on)

You have a really nice project, just improve on it. There is always a way to make it better.

**Pull request merged**
