### PR TITLE
Add table of all repos on github

### PR DESCRIPTION
**Pull request by veggiemonk**
See the results here: https://github.com/veggiemonk/awesome-docker/blob/dc8b627b0edf4248f9a865e693b9ccefa80800a4/data/table.md

This table is not sortable (yet) but it's a start.

### CODE REVIEW

**Comment by agebhar1** [comment]
Very nice @veggiemonk! What are your plans? It's in addition the current representation or a replacement.
You add the fetched data, did you have an idea to update it automatically?

**Comment by veggiemonk** [comment]
@agebhar1 It's not a replacement, just an addition. I thought it would be nice to have some updated data. Yes, they would be automatically fetched. The table could be a way to keep track of the activity in some repos to deprecated/archived those that aren't relevant anymore. What would you like to see in it? What would be the dream feature?

**Comment by vegasbrianc** [comment]
Great idea @veggiemonk  I like this! 👍

**Comment by veggiemonk** [comment]
@agebhar1 @vegasbrianc can someone approve this please ? Only if you think it's good of course....

**Pull request merged**
