### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vegasbrianc**
Added 2 Twitter accounts @dockernews & @thenewstack  and updated the slideshare account to point to the Docker account.

### CODE REVIEW

**Comment by veggiemonk** [comment]
Hey @vegasbrianc 
Thanks a lot! As usual.
Can you send me the link to the video of the conf? I could not find it...

**Comment by vegasbrianc** [comment]
Hi @veggiemonk as soon as Docker publishes my presentation I will send you a link. It seems they are still working on the backlog. Here's the link to my slides - http://www.slideshare.net/Docker/docker-monitoring-55436594

**Comment by vegasbrianc** [comment]
Hi @veggiemonk The videos were posted last night. Here's a link to the Wildcard videos - http://blog.docker.com/2015/12/dockercon-eu-2015-wild-card-day2/ and here is my presentation https://youtu.be/sxE1vDtkYps check out the 21:00 minute mark for my reference of awesome-docker :+1:

**Comment by veggiemonk** [comment]
YEAH!
@vegasbrianc Congratulations on the presentation: http://www.infoq.com/news/2015/12/dockercon-docker-monitoring
You made it to the docker weekly :smile: 
The slides are really good even without the talk I could follow. I clipped some of them on slideshare. 

I never looked too much at InfluxDB, but since we have a lot of problems with logstash (ElasticSearch, Logstash, Kibana stack) to parse the logs, maybe it is time I gave it another try. 
I'll watch the talk tonight (at work right now). Thanks a ton and talk to you soon.

**Comment by veggiemonk** [comment]
Just posted a comment on youtube.

Would you like to be a maintainer of this repo? 
I feel you can have a lot to contribute and maybe you don't want to wait for me to accept your PR.
Anyway, I will add you, you decide how much you can use this resource to your advantages.
By the way, you said in the talk you are using the ELK stack. We have that too but I had so many problems with Logstash and ElasticSearch is clearly not made for developers.
I am going to try influxDB (with one of that nice docker-compose file in your demo) and let you know how it goes.

Really good talk, by the way. I love when I can reproduce the demo at home :smile:

**Comment by vegasbrianc** [comment]
HI @veggiemonk thanks for the comment. Also, I would be more than happy to be a maintainer as well. Look forward to helping out!

Have a good week.

**Comment by veggiemonk** [comment]
Cool. Glad you accepted.
There is this tool: https://github.com/dkhamsing/frankenstein  (it checks for live URLs on a page, it can also correct links in GitHub READMEs)
It really made a big difference...

**Pull request merged**
