### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apurvadave**
I modified the original entry to point to sysdig's monitoring system (versus our open source troubleshooting tool). This seemed to more closely match the other systems in the section (eg prometheus and datadog).

**[Insert the URL to be listed]**

**[Explain what the project is about and why it should be listed]**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- The project submitted conforms to the quality standards outlined in the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- Go to the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md) and read it again.

**RULES (because you probably didn't read the guidelines):**

Links will be tested with [awesome_bot](https://github.com/dkhamsing/awesome_bot). Please make sure your URL to be listed is unique (do some search queries), otherwise put a link at the end of `README.md` file.
 
- FORMAT
  - Use the following format: `[Name](Link) - Description.`
  - `[Name]` should be the title of the project
  - `(Link)` should be pointing to a GitHub repository, not to a website
  - `Description.` should end with a full stop/period
  - For GitHub repositories, add the name of the author with a link to its GitHub account after the description, like `By [@author](GitHub account)`
- ORDER: The entries are in lexical order (English letter order) 
- LABEL (Optional): Add one of the following icons next to the project name like ```[Name](Link) :icon: - Description.```
  - :heavy_dollar_sign: indicates if one needs a paying subscription to use the project.
  - :construction: indicates that the project is a work in progress/beta release.
  - :skull: indicates that the project is obsolete, but still worth mentioning it.

### CODE REVIEW

**Comment by apurvadave** [comment]
Hi @Moshe-Immerman thanks for the comment. 

No the open source version of sysdig is still available. I couldn't quite figure out where to put it - it's not a monitoring tool but rather a troubleshooting tool so doesn't fit in the current category. I planned to do a separate PR to bring it in. Any suggestions where to put it?

Also - regarding the heavy $ I noticed none of the other vendors have it in the monitoring section (assuming because it's called out up top) - more fuel to the fire that the open source sysdig tool belongs elsewhere.

I'll tone down the language on the commercial tool and we can at least get that merged.

**Comment by veggiemonk** [comment]
@apurvadave If you see any entry that is missing the 💲 , we would be grateful for a quick PR!
Highly appreciated

**Comment by veggiemonk** [comment]
Waiting too long

**Comment by apurvadave** [comment]
Apologies I missed this entirely. I'll reopen and resolve it in a timely fashion

**Comment by veggiemonk** [comment]
@apurvadave ping

**Comment by apurvadave** [comment]
@veggiemonk just submitted for Sysdig URL. I'll do another PR to bring open source sysdig back.

**Pull request merged**
