### PR TITLE
Fix owner link for "rocker-compose"

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @veggiemonk 

just fixing a broken link for rocker-compose.

Cheers!

### CODE REVIEW

**Review by gesellix — APPROVED** [review]

**Review by agebhar1 — CHANGES_REQUESTED** [review]
Thanks for your contribution @spekulatius!

The user `@grammarly` is the owner of two tools (rocker and rocker-compose), the check for README.md checks for dupplicate links. We need to fix the rocker-compose data and add a link at the and of the README.md :smiley:

**Comment by spekulatius** [comment]
Ahhh, okay. So the tool is requiring the link to be broken or removed. That's funny! Should we remove the first link ?

**Comment by agebhar1** [comment]
Both links for rocker and rocker-compose should be `By [@grammarly](grammarly)` and we need to add
```
[grammarly]: https://github.com/grammarly
```
at the end of README.md

**Comment by spekulatius** [comment]
Hey @agebhar1,

can you have a look if it's correct now?

Cheers,
Peter

**Review by agebhar1 — APPROVED** [review]

**Comment by agebhar1** [comment]
Looks good @spekulatius :+1: - thank you

**Comment by spekulatius** [comment]
Cool, thanks for checking!

**Pull request merged**
