### PR TITLE
Fix redirect for docker-containerizer

### PR DESCRIPTION
**Pull request by gesellix**
Fixes failing ci test:

    [L206] 301 https://mesos.apache.org/documentation/latest/docker-containerizer  → https://mesos.apache.org/documentation/latest/docker-containerizer/

### CODE REVIEW

**Comment by agebhar1** [comment]
@gesellix CI test failed due to duplication of link(s)
> Issues :-(
> 
> Links 
>
>  All OK ✓
>
> > Dupes 
>
> 1. [L162] https://github.com/netvarun/docket
> 2. [L162] https://github.com/netvarun/

**Comment by gesellix** [comment]
@agebhar1 yeah, the other one is a bit more tricky due to the duplication being triggered by the repo and the author links having the same prefix. I'm not sure how to handle that case. Should we add the link to the list of exceptions?

**Comment by devhkr** [comment]
@gesellix It's because this repo already exits in L370 under the section 'Registry'.

**Comment by agebhar1** [comment]
```
$ grep netvarun README.md --line-number 
162:* [Docket](https://github.com/netvarun/docket) - Custom docker registry that allows for lightning fast deploys through bittorrent by [@netvarun](https://github.com/netvarun/)
370:* [Docket](https://github.com/netvarun/docket) - Custom docker registry that allows for lightning fast deploys through bittorrent by [@netvarun](https://github.com/netvarun/)
```

**Comment by devhkr** [comment]
Cool trick @agebhar1 
Learned something new :smile:

**Comment by agebhar1** [comment]
@devhkr - cool

**Comment by agebhar1** [comment]
... what is the better category for Docket? »Deployment and Infrastructure« or »Registry« @gesellix @devhkr @veggiemonk :thinking: or add link(s) to named link section (at bottom of the file) and leave Docket on both

**Comment by devhkr** [comment]
On the other side, this repo hasn't been updated since 2015 and the author has zero contributions in last year?! Maybe we should remove it.

**Comment by agebhar1** [comment]
I got the same idea @devhkr but I don't know if it's perhaps even working with the latest version of docker image ...

**Comment by devhkr** [comment]
@agebhar1 Maybe it does work. But as Docker has grown rapidly ever since, we don't know if it's still compatible. In addition, the author didn't response any Issues/PRs. The project is definitely obsolete for sure.

**Comment by devhkr** [comment]
@gesellix @agebhar1 

I'll merge this PR and we can discuss this Travis build error further in the Issue section.

**Comment by gesellix** [comment]
👍

**Pull request merged**
