### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vegasbrianc**
Added ImageLayers to the Optimizing Images section

### CODE REVIEW

**Comment by veggiemonk** [comment]
You beat me to it :smile: 
It was in my todo list....
I asked the docker hub team to integrate it directly https://github.com/docker/hub-beta-feedback/issues/143

Thanks a lot for the PR

**Comment by veggiemonk** [comment]
Also if you are interested, there is a refactoring going on on a separate branch (name: refactor). I would love to hear your views on that if you have a chance.

**Comment by vegasbrianc** [comment]
I like the refactor. However I would make a small change for easier reading.  For example, Main Resources would be good to create sub-sections for Blogs, Communities, & General Info. Having subsections would make the list much more reader friendly. Much how you created the Menu section. That is really easy to read and jump to certain sections. Having the same format within the sections would also be beneficial. 

My 2 cents...

**Comment by veggiemonk** [comment]
Nice! Yes, the section are a work in progress and it will look like the menu.
But let's keep going to see how it'll look like..

**Pull request merged**
