### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rafaelspinto**
Added links for [athena](https://github.com/athena-oss/athena) - An automation platform with a plugin architecture that allows you to easily create and share services.

Also a few plugins were added : 
* [athena php plugin](https://github.com/athena-oss/plugin-php) - Plugin for Test Automation using PHP as a development language.
* [athena selenium plugin](https://github.com/athena-oss/plugin-selenium) - Plugin to handle browser automation using Selenium.
* [athena proxy plugin](https://github.com/athena-oss/plugin-proxy) - Plugin to handle a proxy server using Browsermob-proxy.

### CODE REVIEW

**Comment by vegasbrianc** [comment]
Hi @rafaelspinto Thanks for the PR. Athena looks like a really powerful tool. After reviewing your commit can I suggest that we only make one entry for Athena and all the plugins? I would recommend to place Athena in the Dev Tools section as it appears to be the best fit. Then in the description I would list out all the plugins and capabilities.

Thanks again!

**Comment by rafaelspinto** [comment]
hi @vegasbrianc sure, will do it right away ;)

**Comment by rafaelspinto** [comment]
Hi @vegasbrianc , was this what you had in mind c380f02 ?

**Comment by vegasbrianc** [comment]
HI @rafaelspinto Thats perfect thank you! I will wait for the build to complete then merge it.

**Comment by rafaelspinto** [comment]
Hi @vegasbrianc , i think the build failed because of some other links.

**Comment by vegasbrianc** [comment]
@rafaelspinto Build passed and merged.

**Pull request merged**
