### PR TITLE
Remove duplicate "that that"

### PR DESCRIPTION
**Pull request by spekulatius**
Hey,

just improving the readability a bit by removing a duplicate "that".

Cheers!

### CODE REVIEW

**Review by mash1t — APPROVED** [review]
LGTM 👍

**Comment by mash1t** [comment]
@spekulatius this ticket will be merged after https://github.com/veggiemonk/awesome-docker/pull/914 has been approved & completed

**Comment by spekulatius** [comment]
Okay, sounds good @mash1t

**Review by veggiemonk — APPROVED** [review]
Thank you for your contribution

**Comment by spekulatius** [comment]
No worries, happy to help out!

**Pull request merged**
