### PR TITLE
Fix #779 author link

### PR DESCRIPTION
**Pull request by Thomvaill**
Following #779.
I'm really sorry for this oversight!

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Please add the link to the bottom to the others so that they can be reused.

**Comment by Thomvaill** [comment]
I'm sorry but I didn't get what you mean?
I was just fixing the malformed link `[@Thomvaill]` to `[@Thomvaill](https://github.com/Thomvaill)`

**Comment by veggiemonk** [comment]
It is ok. Only duplicate links needs to be at the bottom and reused. Otherwise the tests fail.

**Comment by SuperSandro2000** [comment]
> I'm sorry but I didn't get what you mean?
> I was just fixing the malformed link `[@Thomvaill]` to `[@Thomvaill](https://github.com/Thomvaill)`

The link isn't malformed you forgot to add it to the link list at the bottom.

See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links reference links

**Pull request merged**
