### PR TITLE
MCollective Docker Agent

### PR DESCRIPTION
**Pull request by m4ce**
Hi,

I've written a docker agent for MCollective which builds on top of docker-api and allows for some easy orchestration. I guess it could be useful to some people!

Cheers,
Matteo

### CODE REVIEW

**Comment by veggiemonk** [comment]
Hi @m4ce,

Can you please fix the PR? Some other PR was merged in between... Sorry for the inconvenience

This is a great project!!! Congratulations :smile:

**Comment by vegasbrianc** [comment]
Thanks @veggiemonk I didn't know why it kept failing :+1:

**Comment by veggiemonk** [comment]
@vegasbrianc No worries :smile: This happens quite often. 
In that case just ask nicely to the person who made the PR to update their repo so the PR can be fixed. 
I know it's nothing but I always appreciate when someone make a PR. 
And don't forget to say thanks :D

**Comment by m4ce** [comment]
Hey guys,

resolved the conflict, thanks for merging it!

Matteo

**Pull request merged**
