### PR TITLE
move portainer to web  interfaces

### PR DESCRIPTION
**Pull request by Moshe-Immerman**

### CODE REVIEW

**Comment by agebhar1** [comment]
... need a look into commit history :wink:

**Comment by devhkr** [comment]
@Moshe-Immerman @veggiemonk 

According to PR #[331](https://github.com/veggiemonk/awesome-docker/pull/331#issuecomment-298158342), we decided to put it under `Remote Container Manager / Orchestration`.
So, it should be there as it is.

**Comment by Moshe-Immerman** [comment]
@veggiemonk @devhkr Perhaps I am missing something but the website and description lists it as AN OPEN-SOURCE LIGHTWEIGHT **MANAGEMENT UI** 

I have installed and played around with it a bit, and from what I can see it just exposes native docker API's in a GUI (a very nice one at that)

**Comment by gesellix** [comment]
Portainer also knows Users and Groups, which makes it a bit more than only a UI for the Docker API. Due to its growing popularity and hopefully growing feature set we should keep it under observation and wait until we can better decide about its scope and where to put it in our list?

**Comment by devhkr** [comment]
@Moshe-Immerman 

It was also my first thought to list Portainer under `Web Interface`. However, as @veggiemonk commented on PR 331:

> Web interface is just for docker, not for orchestration which might be confusing.

**Comment by veggiemonk** [comment]
In case of doubt, just imagine yourself as someone who doesn't know much about docker and is looking for a nice, simple [insert name of the section here]... That's what awesome lists are for...

Although the discussion should be extended to refactoring the lists of sections that we have.
See discussion here #392

**Pull request closed without merging**
