### PR TITLE
docker-lock

### PR DESCRIPTION
**Pull request by michaelperel**
A cli-plugin for docker to automatically manage image digests by tracking them in a separate Lockfile.

### CODE REVIEW

**Review by mash1t — COMMENTED** [review]
Hey @michaelperel thank you for the contribution.
I'm not sure if this should be placed in the Security section or Container Composition (if you regard composition as "changing the compose file").
One can make the argument for both categories.
What do you think / why did you put it in security?

**Comment by michaelperel** [comment]
@mash1t Thanks for the review! That’s a great question. I placed it under security because one of the primary use cases of docker-lock is to ensure you don’t run an image that has been potentially updated by a malicious actor.

Given that the tool creates a file with image hashes and has the ability to rewrite your Dockerfiles and docker-compose files with the hashes, I could also see it fitting under Container Composition.

I am perfectly happy with it going under either :)

**Comment by mash1t** [comment]
Thanks for the update 👍 
I'm still not sure but i'd suggest putting it in Container Composition as it mainly tinkers with the docker-compose file and the container version(s) set in it. Security is IMHO one of the nice effects the locking functionality provides.
Let's see what other contributors say.
@agebhar1 @veggiemonk

**Review by veggiemonk — APPROVED** [review]
Nice! Thank you

**Comment by veggiemonk** [comment]
I’m ok to put it in the security section, it makes sense

**Pull request merged**
