### PR TITLE
Added Yacht to web Section

### PR DESCRIPTION
**Pull request by SelfhostedPro**
Yacht is a web interface for managing docker containers with an emphasis on templating to make deployments as easy as possible. Think of it like a decentralized app store for servers that anyone can make packages for.

### CODE REVIEW

**Comment by SelfhostedPro** [comment]
Wasn't sure of the best way to mark as a WiP as I didn't notice any other projects that are. If there's a specific way, let me know and I'll fix it.

**Comment by SelfhostedPro** [comment]
Looks to be something to do with another link:
```
    "other_links_error": [
      [
        "https://www.splunk.com/en_us/blog/cloud/collecting-docker-logs-and-stats-with-splunk.html",
        {
          "ok": false,
          "status": "uri requested responds with a redirect, redirect mode is set to error: https://www.splunk.com/en_us/blog/cloud/collecting-docker-logs-and-stats-with-splunk.html"
        }
```

**Review by agebhar1 — CHANGES_REQUESTED** [review]
Hi @SelfhostedPro thank you for your contribution :+1:

This list uses `:construction:` :construction: to indicate WIP right after the project link (see :skull: for an example).

You can add `By [@SelfhostedPro](https://github.com/SelfhostedPro)` after the project description.

**Comment by SelfhostedPro** [comment]
Perfect, I'll make those changes in a few. (power outage this afternoon)

**Comment by SelfhostedPro** [comment]
Just made those changes. Let me know if there's anything else I need to do.

**Review by agebhar1 — COMMENTED** [review]
👍

**Review by agebhar1 — APPROVED** [review]

**Comment by agebhar1** [comment]
Thanks @SelfhostedPro for your contribution.

**Pull request merged**
