### PR TITLE
Added @dock_station developer centric Docker UI

### PR DESCRIPTION
**Pull request by vegasbrianc**
**https://github.com/DockStation/dockstation**

**This is a new Docker UI aimed at developers creating new projects. The aim is to be able to create projects with the GUI and no CLI. The advantage of the application creating docker-compose.yml files for you to export to other systems.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)
Yup read it :)
- The project submitted conforms to the quality standards outlined in the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)
Looks to be a quality project with lots of documentation
- Go to the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md) and read it again.

**RULES (because you probably didn't read the guidelines):**

Links will be tested with [awesome_bot](https://github.com/dkhamsing/awesome_bot). Please make sure your URL to be listed is unique (do some search queries), otherwise put a link at the end of `README.md` file.
 
- FORMAT
  - Use the following format: `[Name](Link) - Description.`
  - `[Name]` should be the title of the project
  - `(Link)` should be pointing to a GitHub repository, not to a website
  - `Description.` should end with a full stop/period
  - For GitHub repositories, add the name of the author with a link to its GitHub account after the description, like `By [@author](GitHub account)`
- ORDER: The entries are in lexical order (English letter order) 
- LABEL (Optional)
  - $$$ indicates if one needs a paying subscription to use the project.
  <br>Add $$$ next to the project name like `[Name $$$](Link)`
  - BETA indicates that the project is in beta phase.
  <br>Add BETA next to the project name like `[Name BETA](Link)`

### CODE REVIEW

**Comment by Moshe-Immerman** [comment]
I think we should wait until https://github.com/DockStation/dockstation/issues/49 is resolved before including.

**Comment by vegasbrianc** [comment]
Hi @Moshe-Immerman Thanks for your comment. I totally agree this will help potential users but this shouldn't block the addition to the list. If that is the case then every UI from now on would need a comparison to Kitematic and our documentation would need to be updated accordingly. What are your thoughts?

**Comment by Moshe-Immerman** [comment]
@vegasbrianc Perhaps I am missing something, but the list doesn't include any other **Desktop** GUI's for docker (not even Kitematic) - only web and terminal based interfaces?

**Comment by vegasbrianc** [comment]
@Moshe-Immerman You are indeed correct. This maybe needs to move to Development Env's. This has similar functionality as https://github.com/brikis98/docker-osx-dev 

I see you also added additional issues to your original review. I've been away from the project for a bit. Are these requirements you mentioned new now? I cannot find this information in the Contributor Guidelines as a requirement. Let me know as i have several other tools to add this week.

**Comment by Moshe-Immerman** [comment]
@vegasbrianc The issues I raised aren't requirements in the guidelines, they are just my opinions on what needs to be done for this particular project meet the "awesome" bar

**Comment by vegasbrianc** [comment]
@Moshe-Immerman Cool, thanks for the info. Seems according to your issue DockStation/dockstation#50 this is going to be closed source.

**Comment by igor-lemon** [comment]
Hi, guys. Maybe do you have some additional questions about DockStation?

**Comment by vegasbrianc** [comment]
Hi @igor-lemon This is basically done. We are just waiting for the project refactor to complete then we will merge. Cheers!

**Comment by veggiemonk** [comment]
to be merged after #408

**Comment by veggiemonk** [comment]
Hi, 

Due to the refactor, the project has been added in a separate commit: https://github.com/veggiemonk/awesome-docker/commit/5655f27fe7b0ca6070e39ffeffd418ce9f2083c4

Thank you for your PR, we hope that you can contribute to the quality of the projects on list in the future.

Have a good weekend

**Pull request closed without merging**
