### PR TITLE
Docker-Alertd: Send Alerts Based on Container Usage/Statistics

### PR DESCRIPTION
**Pull request by deltaskelta**
docker-alertd:
- is extremely lightweight
- monitors containers based on docker stats API
- monitors CPU usage, memory usage, minimum # of container PIDS
- sends email alerts when limits are reached
- uses a simple json conf file

### CODE REVIEW

**Comment by veggiemonk** [comment]
Hi @deltaskelta,

It seems like a really good idea! I went to see the repo and I couldn't find any explanations.
We value people's time a lot so we want them to find the best projects there is.

As an example, https://github.com/gliderlabs/registrator
It does not have a lot of explanation but there are 2 sections that are really useful. 
* How to setup the project
* How to use it (an example)

Could you add those to your project's README? 

Our goals is also to help developers to make great projects. 
So a good start would be to look at other projects and take good ideas from them. 

Docker-sync has a very simple website hosted on github pages, that really improves the reach of the project (more people come and check it out). http://docker-sync.io/

Some developers go really the extra miles to explain what their project is all about such as https://github.com/grammarly/rocker

So let us know if you need any help. Write examples and how to setup the project. Then come back here and ping us. All right?

Have a good day and keep on making great software!

The awesome docker team 

@vegasbrianc @gesellix @dmitrytokarev @veggiemonk

**Comment by deltaskelta** [comment]
@veggiemonk, I modified the README file to have a a better explanation, please let me know what you think

**Comment by dmitrytokarev** [comment]
wow build system is just flaky lately...

**Comment by veggiemonk** [comment]
@dmitrytokarev see in the chat (gitter)

**Pull request merged**
