### PR TITLE
added docker-box in Web-interface

### PR DESCRIPTION
**Pull request by ravigadila**
[Docker-box](https://github.com/MicroPyramid/docker-box): Web interface to run full blown OS containers within seconds instead of setting up virtual machines and you get all the benefits of containers like instantaneous backups(commits), easy start and stop and the awesome feature of pausing your container etc.

Why docker-box?
  - UI to run containers easily.
  - Takes care of networking.
  - User management.
  - Host and containers statistics.
  - Create backups of containers.
  - Web based terminal session for containers.

### CODE REVIEW

**Comment by veggiemonk** [comment]
Hi @ravigadila 

It seems like a really good idea! I went to see the repo and I couldn't find any explanations.
We value people's time a lot so we want them to find the best projects there is.

Why did you put it in the `Infrastructure` section if it's a web interface? 
The description is not really clear, could you make it so that even people that are new to docker might understand what it does and how to use it?

As an example, https://github.com/gliderlabs/registrator
It does not have a lot of explanation but there are 2 sections that are really useful.

 *   How to setup the project
 *   How to use it (an example)

Could you add those to your project's README?

Our goals is also to help developers to make great projects.
So a good start would be to look at other projects and take good ideas from them.

Docker-sync has a very simple website hosted on github pages, that really improves the reach of the project (more people come and check it out). http://docker-sync.io/

Some developers go really the extra miles to explain what their project is all about such as https://github.com/grammarly/rocker

So let us know if you need any help. Write examples and how to setup the project. Then come back here and ping us. All right?

Have a good day and keep on making great software!

The awesome docker team

@vegasbrianc @gesellix @dmitrytokarev @veggiemonk

**Comment by ravigadila** [comment]
Hi @veggiemonk 

I have changed the category to 'web-interface'. Also modified the README.md to explain a bit more what dockerbox does,  thanks for your suggestions and please let me know if you have any other issues or suggestions.

**Comment by veggiemonk** [comment]
Hi @ravigadila,
Thank you very much for the changes.

The project is still quite blurry: 
* Why is it called docker-box? 
* What is the difference between that and another UI such as `DockerUI` ? 
* What does `full blown OS containers` means? 
* Does it work with multiple hosts?
* How does it connect to Docker? via socket?

I cannot understand what is this project is about because it does not seems simple. 

All those details are hidden in the code and we value people's time a lot, so can you make it super clear and simple: 
* what is this project? 
* what does it do? 
* how to use it? 
* how it does it compares to others from the same category ?

We want to stay objective because we want to be honest about the project listed here. 

Do you understand my concerns?

**Comment by vegasbrianc** [comment]
Hi @ravigadila How is the PR going? Do you have an update for us?

Thanks!

**Pull request closed without merging**
