### PR TITLE
Add gitkube

### PR DESCRIPTION
**Pull request by ashishmohite**
**https://github.com/hasura/gitkube**

**Gitkube is a tool for building and deploying docker images on Kubernetes using git push.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- The project submitted conforms to the quality standards outlined in the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md)

- Go to the [contribution guidelines](https://github.com/veggiemonk/awesome-docker/blob/master/CONTRIBUTING.md) and read it again.

**RULES (because you probably didn't read the guidelines):**

Links will be tested with [awesome_bot](https://github.com/dkhamsing/awesome_bot). Please make sure your URL to be listed is unique (do some search queries), otherwise put a link at the end of `README.md` file.
 
- FORMAT
  - Use the following format: `[Name](Link) - Description.`
  - `[Name]` should be the title of the project
  - `(Link)` should be pointing to a GitHub repository, not to a website
  - `Description.` should end with a full stop/period
  - For GitHub repositories, add the name of the author with a link to its GitHub account after the description, like `By [@author](GitHub account)`
- ORDER: The entries are in lexical order (English letter order) 
- LABEL (Optional): Add one of the following icons next to the project name like ```[Name](Link) :icon: - Description.```
  - :heavy_dollar_sign: indicates if one needs a paying subscription to use the project.
  - :construction: indicates that the project is a work in progress/beta release.
  - :skull: indicates that the project is obsolete, but still worth mentioning it.

### CODE REVIEW

**Comment by moshloop** [comment]
@ashishmohite gitkube is certainly very awesome - but I think the dependency on k8s would exclude it from this list which is focused on tools that will work on docker alone.

**Comment by ashishmohite** [comment]
@moshloop does that mean i should close this PR ?

**Comment by veggiemonk** [comment]
Hi all,

It's interesting because I just had that discussion the other day mentioning that people don't say "docker container" anymore because we might not use docker to build and deploy container.

And docker is not really docker in a sense that it's called moby which still confuses me time to time.

I feel like we shouldn't be too strict on this whole docker (the company) brand name and focus more on the open source side of the container and the CNCF.

What do you guys think? @vegasbrianc @gesellix @agebhar1 @moshloop

**Comment by veggiemonk** [comment]
@ashishmohite wait before closing please 👍

**Comment by agebhar1** [comment]
For me it's totally okay to be less restrictive and more »container«-ized :+1:

**Comment by vegasbrianc** [comment]
Docker is the core component of K8s. Just saying. I would agree with @agebhar1 and make the repo more Container-Native

**Comment by veggiemonk** [comment]
I believe the way forward is to embrace the native container approach.

Unless someone completely disagree I would approve this PR.

**Pull request merged**
