### PR TITLE
Add Kurtosis to list of testing tools

### PR DESCRIPTION
**Pull request by leeederek**
Hey team! We'd like to add Kurtosis to the list of testing tools. 

*What is Kurtosis?* 
Kurtosis is a build system for multi-(docker)container test environments.  

*What is Kurtosis for?* 
Kurtosis is for engineers who dev against distributed systems/applications and who experience pain when trying to configure multi (Docker) container environments for their testing workflows. 

Kurtosis can be used locally without the need to sign up and is free-forever under a source-available license (BSL). 

*Items explicitly required from the Quality Standards guide:*
- We linked out to our Github: https://github.com/kurtosis-tech/kurtosis
- We have a [README on our Github](https://github.com/kurtosis-tech/kurtosis#readme)
- We have content about how to setup/install the project (in our [Github README](https://github.com/kurtosis-tech/kurtosis#to-start-using-kurtosis) and on our [docs](https://docs.kurtosis.com/install)),
- We also published lots of great examples (with more to come) on: [Github](https://github.com/kurtosis-tech/awesome-kurtosis#awesome-kurtosis-) and in our [docs](https://docs.kurtosis.com/). 

I followed the [Quality Standards](https://github.com/veggiemonk/awesome-docker/blob/master/.github/CONTRIBUTING.md#quality-standards) you guys wrote, but please let me know if you've got any questions about Kurtosis or if we missed something!

Thanks

### CODE REVIEW

**Review by mashb1t — COMMENTED** [review]
Hey @leeederek, kurtosis looks promising and the documentation is of outstanding quality.

Your website states that you are currently in build mode and the tool has not yet reached a maturity of 1.0.0, which hints to me that the project is WIP. Is this correct?

If yes please add the WIP flag as mentioned in the PR template / contribution guidelines.

**Comment by leeederek** [comment]
Hey @mashb1t! Thanks for the feedback and quick reply!

Regarding the "build mode" text on our website, we're going to update our website very soon to remove that (by the end of next week to be exact, so in 6 business days).

Regarding us being below 1.0.0, is that something you require for us to not have the "WIP" flag? That distinction wasn't clear in the Community Standards guidelines, but let me know if it is. We'd prefer not to have that flag and are saving the big 1.0.0 release for a big feature/change on our roadmap.

**Review by mashb1t — APPROVED** [review]
Hey @leeederek, thank you for the explanation and the additional infos.
No, you're not required to have version 1.x to be on the list or marked as stable, but 0.x in combination with the text on your website hinted to the project being WIP.
Let's give you the benefit of the doubt for the website update.
All the best for the future development of your project 👍

**Comment by leeederek** [comment]
Thank you!

**Pull request merged**
