### PR TITLE
Added OpenDevSecOps

### PR DESCRIPTION
**Pull request by pdparchitect**
https://github.com/opendevsecops

This project aims to create several security solutions for ci/cd pipelines and cloud infrastructures.

### CODE REVIEW

**Comment by veggiemonk** [comment]
@vegasbrianc @agebhar1 @dmitrytokarev @gesellix @moshloop what do you think ?

**Comment by agebhar1** [comment]
@veggiemonk will leave my feedback in the next day(s)

**Comment by agebhar1** [comment]
As far I can see OpenDevSecOps is a bunch of selected 3rd party security tools. I agree with @veggiemonk that almost all repositories contains only a README with it's docker command, e.g. [https://github.com/opendevsecops/docker-sqlmap](docker-sqlmap) is only a repacking of `jdecool/sqlmap:latest` without any credits. Without any explanations I can't see a relation to docker beside of containerized tools.

**Comment by pdparchitect** [comment]
Many security tools come with docker containers which are not often up-to-date or cannot be trusted due to various reasons. Besides all the other things we do with terraform, the containers are built to provide a level of convenience and extended trust that at the very least we will check the container is built to some standard. There are a lot of things that needs to done in this regard but we are working slowly to progress on all matters.

That particular example with sqlmap is part of the long list of blindspots - it is a shortcut and yes we will be providing our own Dockerfiles as well some basic readme to provide credits where due.

**Comment by veggiemonk** [comment]
@pdparchitect Right now, each repo is just a dockerfile with the bear minimum readme.

This does not meet the requirements as listed here: https://github.com/veggiemonk/awesome-docker/blob/master/.github/CONTRIBUTING.md#quality-standards

Ping us back when the project has improved its usability.

**Pull request closed without merging**
