### PR TITLE
Add Nebula

### PR DESCRIPTION
**Pull request by naorlivne**
http://nebula.readthedocs.io/en/latest/

A Docker orchestrator for distributed apps (IOT/remote appliances, distributed servers)

### CODE REVIEW

**Comment by devhkr** [comment]
Hi @naorlivne 

Thanks for sharing the tool.

Currently, the Awesome Docker team are refreshing the categories (see issue #393). So, it is possible that your contribution is no longer correct and/or the suggested tool has to be (re)moved.

Until we reordered the categories, all incoming PRs will be on hold.

Thank your for your understanding.

The Awesome Docker Team

**Comment by naorlivne** [comment]
Added requested change, pointing to the GitHub Nebula organization rather then a single repo as the project include of 5 (and growing) repos, a minimum of 2 (api-manager and worker-manager) are required to run Nebula.

**Comment by naorlivne** [comment]
Travis build seems to fail with an unclear message about `The command "awesome_bot README.md --white-list wiki/Installing,slideshare,awesome-docker.svg,edit/master,sindresorhus/awesome,ashmckenzie,shortcircuit.net.au,photo777.org,adrianmouat,redhat,viget,meros,toedter,datadoghq,amazon.cn,blog.codeship.com,swarm-v-fleet,amazon.com,blogs.splunk.com,docs.mesosphere.com,containership.io,gliderlabs.com,twistlock.com,shipyard-project.com,dashboard.tutum.co,vimeo.com,docs.microsoft.com,eclipse.org,codenvy.io,gitter.im,sebgoa.blogspot.be,mindmeister.com" exited with 1.` on pushing the requested change, can anyone assist?

**Comment by veggiemonk** [comment]
@naorlivne Don't worry about travis failing. It's not your modification. We are in the middle of refactoring the whole list and the sections and other details so this will be rebased and merged next week.

**Comment by veggiemonk** [comment]
Hi, 

Due to the refactor, the project has been added in a separate commit: https://github.com/veggiemonk/awesome-docker/commit/5655f27fe7b0ca6070e39ffeffd418ce9f2083c4

Thank you for your PR, we hope that you can contribute to the quality of the projects on list in the future.

Have a good weekend

**Pull request closed without merging**
