### PR TITLE
add :skull: to all repo's with a last commit > 500 days

### PR DESCRIPTION
**Pull request by Moshe-Immerman**
I modified awesome_bot to check the last commit age and this was the output:

 https://github.com/odewahn/docker-jumpstart/ => last commit was 788 days ago
https://github.com/dwyl/learn-docker => last commit was 759 days ago
https://github.com/p8952/bocker => last commit was 765 days ago
https://github.com/abesto/docker-compose-graphviz => last commit was 716 days ago
https://github.com/toscanini/maestro => last commit was 1494 days ago
https://github.com/CenturyLinkLabs/zodiac => last commit was 760 days ago
https://github.com/netvarun/docket => last commit was 963 days ago
https://github.com/humblec/dockit => last commit was 1046 days ago
https://github.com/longshoreman/longshoreman => last commit was 987 days ago
https://github.com/dockerana/dockerana => last commit was 1013 days ago
https://github.com/gocardless/logjam => last commit was 709 days ago
https://github.com/tubesandlube/blimp => last commit was 902 days ago
https://github.com/CenturyLinkLabs/panamax-ui => last commit was 570 days ago
https://github.com/ooyala/atlantis => last commit was 568 days ago
https://github.com/silarsis/docker-proxy => last commit was 502 days ago
https://github.com/zchee/h2o-proxy => last commit was 596 days ago
https://github.com/cpuguy83/docker-grand-ambassador => last commit was 970 days ago
https://github.com/factorish/proxy => last commit was 873 days ago
https://github.com/icecrime/docker-mon => last commit was 929 days ago
https://github.com/crosbymichael/dockersql => last commit was 1042 days ago
https://github.com/Electrofenster/dockerding-on-rails => last commit was 642 days ago
https://github.com/mutable/container-factory => last commit was 864 days ago
https://github.com/wercker/dlayer => last commit was 583 days ago
https://github.com/jlhawn/dockramp => last commit was 501 days ago
https://github.com/djosephsen/skinnywhale => last commit was 689 days ago
https://github.com/kstaken/dockerfile-examples => last commit was 656 days ago
https://github.com/clusterhq/powerstrip => last commit was 610 days ago
https://github.com/fgrehm/devstep => last commit was 802 days ago
https://github.com/bsideup/forward2docker => last commit was 528 days ago
https://github.com/awvessel/vessel => last commit was 791 days ago
https://github.com/rancher/sherdock => last commit was 719 days ago
https://github.com/dockunit/platform => last commit was 666 days ago
https://github.com/cortexmedia/Beluga => last commit was 716 days ago
https://github.com/benzaita/docker-do => last commit was 675 days ago
https://github.com/CenturyLinkLabs/dray => last commit was 602 days ago
https://github.com/mattes/fugu => last commit was 768 days ago
https://github.com/bubenkoff/vagrant-docker-example => last commit was 756 days ago
https://github.com/GDSSecurity/Docker-Secure-Deployment-Guidelines => last commit was 502 days ago
https://github.com/ashmckenzie/percheron => last commit was 758 days ago

### CODE REVIEW

**Comment by devhkr** [comment]
@Moshe-Immerman Great job! But how did you modify ```awesome_bot```? It would be nice to have such an implementation here. So, we don't have to check every link for the last commit.

**Comment by gesellix** [comment]
Great idea! There's only one concern where I guess we should check the actual repo before adding the 💀 : In cases where a repo is "done" in terms of "it doesn't need any maintenance and as such won't receive any commits". I wouldn't mark such a repo as deprecated or unmaintained.

**Comment by veggiemonk** [comment]
Great job! 

Why the tests are failing ?
Does that means that we should reject any project that is inactive > 500 days ?

**Comment by Moshe-Immerman** [comment]
I added the age check for updated lines only - as this PR contains lots of old repo's it fails correctly.  In theory it should ignore lines with a 💀 , but that was a little more complicated with the existing code.

It is a throwaway github account - Github applies aggressive rate limiting to unauthenticated API access.

**Comment by veggiemonk** [comment]
Alright, I see.

I agree with @gesellix Not all repo are archived or should have the 💀 . Some project are feature complete and don't need anymore modification or maintenance. 
For those repo I would just remove the 💀 and leave it as is. For example: `docker-compose-graphviz` it works, it does what it says AFAIK.
Let's check the projects 
Good initiative @Moshe-Immerman 👍 

Thanks

**Comment by agebhar1** [comment]
:+1: @Moshe-Immerman

But I also agree with @gesellix that the period of the last commit is not adequately but necessary to add :skull: to the project. To mark a project as 'under investigation' we might add the number of open issues (logical) or open push requests with there timestamps.

For now I promote @veggiemonk 
> Let's check the projects

... maybe each of us takes 1/5th of the projects and check them?

**Comment by veggiemonk** [comment]
We don't need to check all +300 projects, just those in this PR.

**Comment by Moshe-Immerman** [comment]
I reverted a few for utilities that were small and didn't have major open issues - but I think anything that is more than a couple hundred lines of code - it can never really be "done"

**Comment by veggiemonk** [comment]
If someone else agree on those change we can merge this.

**Comment by agebhar1** [comment]
I agree to this PR as @Moshe-Immerman 
> reverted a few for utilities that were small and didn't have major open issues

and under the premise that we update/add a precise description to `README.md` legend for :skull: and the others too.

IMO a tool's last commit might be a long time ago but if its still working it should not imply that it is abandoned. Remember from UNIX philosophy:

> Make each program do one thing well.

**Comment by gesellix** [comment]
👍 
Let's give it a try - everything is in Git and nothing is carved in stone :-)

**Pull request merged**
