### PR TITLE
Add Better Stack to monitoring services

### PR DESCRIPTION
**Pull request by ayoisaiah**
Add [Better Stack](https://betterstack.com/) for uptime monitoring and logging for Docker containers and the apps that run inside them.

### CODE REVIEW

**Comment by mashb1t** [comment]
Hey @ayoisaiah,

can you please point us to the reference where docker is mentioned on the website? I could neither find a mention on the index  nor on the pricing page.

**Review by veggiemonk — APPROVED** [review]
Thanks for contributing

**Comment by veggiemonk** [comment]
@mashb1t sorry!!!🙇‍♂️🙇‍♂️

I am on my phone and just saw it was in the paying services. 

I think you are totally right 

We should point to the docker part. I'll fix this asap.

**Comment by veggiemonk** [comment]
Ping @ayoisaiah

**Pull request merged**
