### PR TITLE
Adds WeDeploy to readme

### PR DESCRIPTION
**Pull request by albertmourato**

### CODE REVIEW

**Comment by veggiemonk** [comment]
Hi @albertmourato,

As mentioned in the contribution guidelines:
```
To be on the list, the project must have:

How to setup/install the project
How to use the project (examples)
```

The github link in this pull request is an example of ? 

If you want to advertise your platform, feel free to add it in https://github.com/veggiemonk/awesome-docker#caas

Those projects are meant for open source project. I don't see your platform being open source. 
Did I miss something ?

**Comment by albertmourato** [comment]
Hi @veggiemonk,
Sorry for this inconvenience.
Actually, the URL that I added to the PR is from a Github Organization maintained by us that contains lots of applications configured to be deployed to WeDeploy.
Part of the platform is composed of Open Source projects as you can see [here](https://github.com/wedeploy/).
Our platform is not necessarily paid since we provide a plan with no costs and a great number of resources.

**Comment by veggiemonk** [comment]
Hi @albertmourato 

Thank you for the quick reply. 


I want to help you build a successful project, so here is my recommendation:

Since your platform is a composition of open source projects, I would suggest that you add it to  https://github.com/veggiemonk/awesome-docker#caas and write in the description that it is build on top of open source projects. Just put the website https://wedeploy.com as the main link.

Why I ask that ? Because the goal is to make it clear for people what it is. If someone as to read a lot of text and click and search everywhere to find the information they want ( such as "How I do install that?" and "How do I use that?" ), then it makes people waste time. The wedeploy website is pretty good and clear, with documentation and a blog and everything. My recommendation is to use that rather than a repo that is almost empty without any explanations.  

To be on the list, any github project has to follow the rules. The example project that you linked here does not. If you want an example of good README.md, here is a good example: https://github.com/jwilder/nginx-proxy 

I hope it helps.

Ping me here when I can review the changes.

**Comment by veggiemonk** [comment]
ping @albertmourato

**Comment by albertmourato** [comment]
Hi @veggiemonk , sorry about the delay.

I'm too busy at the moment so that I'll close this for now.
I really appreciate all your attention.

Thank you a lot and sorry for this inconvenience,
Albertinin

**Pull request closed without merging**
