### PR TITLE
adding article on dockerfile for beginners and jenkins 2.0

### PR DESCRIPTION
**Pull request by ramitsurana**

### CODE REVIEW

**Comment by veggiemonk** [comment]
@ramitsurana Thanks for the PR. 
Can you remove the Docker for beginner as we already have tons of those and add the jenkins article to Continuous deployment section ?

**Comment by ramitsurana** [comment]
@veggiemonk Thanks for the feedback.I have made the changes accordingly and added some thing.Let me know if you find it worthy enough.

**Comment by veggiemonk** [comment]
Cool thank you for the slide. They are great!
The branch still had conflict but they are resolved now.

**Comment by ramitsurana** [comment]
Thanks a lot !! @veggiemonk

**Pull request merged**
