### PR TITLE
add a few section descriptions

### PR DESCRIPTION
**Pull request by Moshe-Immerman**

### CODE REVIEW

**Comment by devhkr** [comment]
What is conflicting here?

**Comment by agebhar1** [comment]
@devhkr follow the link [web editor](https://github.com/veggiemonk/awesome-docker/pull/431/conflicts)

**Comment by devhkr** [comment]
@agebhar1 I saw that, but what does ```=======``` mean?

**Comment by agebhar1** [comment]
@devhkr above `=======` is the content added by this commit and below the content which is on `master` but not (yet) within this commit

ad hoc I didn't find a formal explanation but it's a diff format like https://askubuntu.com/a/56965

**Pull request merged**
